language: python
sudo: false
python:
  - "3.8"
install:
  - pip install -r requirements-dev.txt
  - python setup.py develop
script:
  py.test --cov storageprovider --cov-report term-missing tests
after_success:
  - coveralls