name: Storageprovider backend tests

on:
  push:
    paths:
      - storageprovider/**
      - tests/**
      - .github/workflows/storageprovider.yaml
      - pyproject.toml
      - requirements*.txt

env:
  PYTHON_VERSION: "3.11"

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install python requirements
        env:
          HATCH_BUILD_NO_HOOKS: true
        working-directory: ./
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip --version
          pip install pip-tools
          pip-sync requirements-dev.txt
          pip install -e .

      - name: Python tests
        run: |
          source venv/bin/activate
          pytest tests --exitfirst --capture=no -vvv --full-trace
